version: 0.0
os: linux

files:
  - source: /    # This reflects the extracted contents from project.zip
    destination: /var/www/my-app # Destination directory on the instance (you can modify this)

permissions:
  - object: /var/www/my-app
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
      - directory
    recurse: true

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh  # Script to install dependencies
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/change_permissions.sh    # Script to change permissions
      timeout: 300
      runas: root

    - location: scripts/copy_nginx_conf.sh   # Script to copy custom nginx.conf to /etc/nginx/
      timeout: 300
      runas: root

    - location: scripts/restart_nginx.sh   # Restart or reload Nginx after files are installed
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh          # Script to start the server
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh      # Script for validation (health check)
      timeout: 300
      runas: root